### ISSUE TITLE
Delay message with Insights

### ISSUE THREAD

**Issue by rgr2000** [MicrosoftDocs/OfficeDocs-WorkplaceAnalytics#228] opened 2021-05-10 02:43 UTC
It will be interesting to know who to trigger this option if the option to delay the message does not show up automatically in outlook 

alias: rgomez 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46f983da-af4c-d975-445b-77fb8f307848
* Version Independent ID: 0cf725f8-0abf-465e-b031-396344f54cb1
* Content: [Delay delivery plan in MyAnalytics - Workplace Intelligence](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/delay-delivery)
* Content Source: [WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/WorkplaceAnalytics/MyAnalytics/Use/delay-delivery.md)
* Product: **mya**
* GitHub Login: @paul9955
* Microsoft Alias: **v-mideh**

**Comment by rgr2000** [comment] 2021-05-12 06:27
Hello Paul,

Both options are completed the issue here is that the delay to send email does not show up when I used a DL, if I do not use a DL it shows just fine.

Ricardo

**Comment by paul9955** [comment] 2021-05-26 05:01
Hi Ricardo,

Thank you for your patience on this issue. I've confirmed with the product team the behavior that you witnessed: The delay-delivery capability _does not work with DLs_. 
I appreciate your bringing this to our attention because it helped me fill a gap in our documentation. We now state this limitation &ndash; for example, see the end of the first paragraph in the [Delay delivery](https://docs.microsoft.com/en-us/workplace-analytics/myanalytics/use/mya-notifications#delay-delivery) topic. 

I'll close this issue now. If you have further comments or questions, feel free to re-open it.

Thank you, 
-- paul9955

**Closed by paul9955** 2021-05-26 05:01 UTC

**Comment by rgr2000** [comment] 2021-05-26 15:14
Thank you Paul, maybe a future opportunity 😊 also it will be good to trigger this manually is an amazing feature much better that delay option

Ricardo
